Fitx/apply audit
Lambda256/luniverse-token-protocol pull request #9
Opened 2021-05-06 08:16 UTC by ethanLambda

아래의 업무 리스트 중 audit 문서에 대한 내용을 모두 수정 완료하였습니다.
리포트 분석 & 컨트렉트 수정 진행
(리뷰회의, offline code review는 아직 진행 되지 않음)

1. 루니버스 토큰 컨트랙트 audit 수정
    1. audit 리포트 분석한 뒤 리뷰 회의
    2. 토큰 컨트랙트 수정 후 pull request 올린 뒤, offline code review
    3. [https://github.com/Lambda256/luniverse-token-protocol](https://github.com/Lambda256/luniverse-token-protocol)

2021-05-07 00:59 UTC, martin4624 commented on contracts/OwnableNew.sol
> +}
마지막에 newline 이 빠져있습니다.

2021-06-10 05:48 UTC, james-lim requested changes

2021-06-10 05:48 UTC, james-lim commented on contracts/MainToken.sol
> +    mint(_initialSupply);
@martin4624 @ethanLambda 
생성자에서 mint 를 하게 되면 아래 mint 함수에서 totalSupply 에 initialSupply 만큼 더해지게 됩니다. 그런데 ERC20Token의 생성자에서 이미 totalSupply 가 initialSupply 로 세팅되었기 때문에 실제 totalSupply는 initialSupply 값의 2배가 설정되게 됩니다. 만약 mint 함수를 호출하고 싶다면 ERC20Token contract 도 수정해야 하는데, 그러면 ERC20Token 을 상속받은 다른 컨트랙트들도 영향이 가게 됩니다. 그냥 기존 코드로 남겨 놓는 것이 어떨까요?

2021-06-10 05:49 UTC, james-lim commented on contracts/LinearMintableToken.sol
> +  uint256 public mintedAmount = 0;
이 변경은 필요 없어보이는데 굳이 넣은 이유는 뭔가요?

2021-06-10 05:54 UTC, james-lim commented on contracts/ERC20Token.sol
> +  mapping(address => uint256) private _balances;
노션에는 private 으로 할 경우 에러가 발생한다고 써 있는데 internal 로 하는 거 아니었나요?

2021-06-10 05:54 UTC, ethanLambda commented on contracts/MainToken.sol
> +    mint(_initialSupply);
저도 테스트 때 mint를 넣으려는것을 취소하려고 했는데 James님 말대로 수정되는 것이 너무 많기 때문에 기존 코드로 남겨두는게 맞다고 생각합니다.

2021-06-10 06:08 UTC, ethanLambda commented on contracts/ERC20Token.sol
> +  mapping(address => uint256) private _balances;
아 네 private으로 할 경우 ERC20Token을 상속받아서 쓰는 다른 컨트렉트에서 에러가 나기 때문에 internal로 해야 됩니다. 잘못 수정한것 같습니다.

2021-06-10 06:25 UTC, ethanLambda commented on contracts/LinearMintableToken.sol
> +  uint256 public mintedAmount = 0;
위에 private 변수는 LMT-01S: The SECONDS_IN_A_DAY variable of the LinearMintableToken contract has no explicitly set visibility specifier. 오딧 문서의 위 항목에 따라서 지정해 주었는데 필요 없어보이긴 합니다. 그리고 mintedAmount=0은 오래되어서 기억은 잘 안나는데 계속해서 증가하는 변수로 쓰여지는 것으로 확인되어서 =0을 빼는것이 맞는것 같습니다.

2021-06-10 08:14 UTC, martin4624 commented on contracts/MainToken.sol
> +    mint(_initialSupply);
@james-lim 네. ERC20Token 에서 mint 함수 호출합시다.

2021-06-11 01:09 UTC, james-lim commented on contracts/ERC20Token.sol
> +  mapping(address => uint256) private _balances;
@ethanLambda internal 로 수정바랍니다.

2021-06-11 04:03 UTC, james-lim approved these changes

2021-06-11 04:05 UTC, merged